
version: "3"

services:
  signer:
    hostname: signer
    image: bridge:latest
    volumes:
      - /replace/this/with/keys/path/:/root/keys  # map the path where the file specified by "secret_key_name" exists
    environment:
      - SWAP_ENV=TESTNET
      - MODE=signer
      - db_username=memyselfandI
      - db_password=supersecret
      - db_host=url_to_db.com

      # scrt keys config
      - secret_key_name=t1
      - secret_key_file=t1.key
      - secret_key_password=12345678

      # eth key option 1 - hardcoded private key
      - eth_private_key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa   # ethereum private key
      - eth_account=0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                     # ethereum account address

      # eth key option 2 - pkcs11 module (only softhsm supported currently)
      # volumes: (you may want to map the token storage path to a path inside the container)
      #   - /path/to/tokens:/root/hsm/tokens/
      # environment:
      #   - token=token
      #   - user_pin=1234
      #   - label=label
