name: Python Checking

on: [push, pull_request]

jobs:
  analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Module dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --exclude __init__.py --count --max-complexity=10 --max-line-length=127 --statistics .
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile .pylintrc .
    - name: Typecheck with mypy
      run: |
        pip install mypy
        mypy .
    - name: Safety Check
      run: |
        pip install safety
        safety check